### ISSUE TITLE
Game crash in startup

### ISSUE THREAD

**Issue by Bogdan-G** [yogpstop/QuarryPlus#24]
Hello. Use:
Java 1.7.0_67 x64
MC 1.7.10 and Forge .1286
BC: 6.2.6 and 6.3.1
QuarryPlus: 2.0.1 release and last snapshot QuarryPlus-1.7.10-9a33a59b29b6af0d4da231f659aefaa4d47b6eb6
NEI: 1.0.3.77
CoFHCore: 3.0.0B9-93/94
CodeChickenCore: 1.0.4.29-universal
CodeChickenLib: 1.1.1.110-universal

here are some crash-reports with different versions of mods:
http://pastebin.com/fsvR4dkH
http://pastebin.com/d4NrhZLC
http://pastebin.com/QVWSqtLz
http://pastebin.com/yn2zcjHn
http://pastebin.com/z1fJL1Fw
http://pastebin.com/s66d3F1e

**Comment by Xee1** [comment]
I think is BC 6.3.x, with 6.2.x work.

**Comment by Bogdan-G** [comment]
Xee1, http://pastebin.com/QVWSqtLz

**Comment by Xee1** [comment]
Mh, have you selected  QuarryPlus for Builldcraft 6.2.X folder?

**Comment by Bogdan-G** [comment]
Xee1, yes

**Comment by Xee1** [comment]
Oh ok, well , I don't know, I think only @yogpstop can fix

**Comment by yogpstop** [comment]
It will fixed in next release.
In BC 6.2.X, it can be reproduced.

**Comment by yogpstop** [comment]
Fixed on 1051a3bc488539625fb501931c21507758fc8600
