### ISSUE TITLE
Placer Plus not working

### ISSUE THREAD

**Issue by armywolf08** [yogpstop/QuarryPlus#29]
I do believe it is an issue with Group manager. Any reason as to how to fix this?

**Comment by yogpstop** [comment]
Essential's Group Manager?
I need more information around setting.

**Comment by armywolf08** [comment]
I fixed it I had to search for your comand.commandhandler thing

**Comment by yogpstop** [comment]
Sorry. Does your message mean this issue is resolved?
If true, I'll close this issue.

**Comment by armywolf08** [comment]
Yes its resolved.
