### ISSUE TITLE
Compatibility with Buildcraft 7.X

### ISSUE THREAD

**Issue by Xen1290** [yogpstop/QuarryPlus#32]
Hi @yogpstop , could you add compatibility with Buildcraft 7?

**Comment by Xee1** [comment]
Any news @yogpstop ? Buildcraft 7.0.6 is out and stable.

**Comment by yogpstop** [comment]
I think latest QuarryPlus already has compatibility with BuildCraft 7.X.
Do you have crash?

**Comment by Xen1290** [comment]
Fixed. Sorry, I've forgotten to close the issue. I think it was another bc addon that did that crash. 

Just one thing, you will change your texture to match new bc 7 style?

**Comment by yogpstop** [comment]
I'm so sorry. But I have no plan to change textures.

**Comment by Xen1290** [comment]
Ok, no problem, thank you for answer!

**Comment by Ace199102840** [comment]
i know this is old but i do have a crash that i think has to do with quarryplus and buildcraft-7.0.22 .  worth a shot... http://pastebin.com/606RHhVg

**Comment by Bogdan-G** [comment]
@Ace199102840 You download mod version for minecraft 1.4.5

> last files for MC 1.7.10:
> http://sourceforge.net/projects/yogpstopmcmods/files/Alpha/jar/QuarryPlus/Minecraft%201.7.10%20with%20BC%206.1.X%20or%20newer/
> file date modifier 2015-07-02 or newer

**Comment by Ace199102840** [comment]
@Bogdan-G  ya i just realized after posting i had the wrong version. thank you though :)

**Comment by Bogdan-G** [comment]
@Ace199102840 you're welcome
