### ISSUE TITLE
Crash when rendering the laser block

### ISSUE THREAD

**Issue by Ivorforce** [yogpstop/QuarryPlus#34]
Hey,

this crash http://paste.ee/p/Trgr8 occurs during the profile times by MystCraft (reportedly). I had a quick look and you seem to call https://github.com/yogpstop/QuarryPlus/blob/master/src/main/java/com/yogpc/qp/render/RenderLaserBlock.java#L33 - which would cause that bug.
Keep in mind metadata can always be a value you are not anticipating, so getting a 15 (or 8) out of it is entirely valid. Use ForgeDirection.getOrientation(metadata) instead, and expect the INVALID direction for a bad return value.

**Comment by knoeki** [comment]
Just pointing out, it was me having this issue, Ivorforce just reported it here for me ^^;

**Comment by yogpstop** [comment]
Fixed on 8b3bf12ab50cac2de52a7934155fef5a79271daa
